OCR_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uploader/urls.py
from django.urls import path
from uploader.views import home

urlpatterns = [
    path('', home, name='home'),
]

core/models.py
from django.db import models

# Create your models here.

uploader/models.py
from django.db import models
from core import utils
import hashlib
from PIL import Image
import pytesseract


class ImageFileManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(models.Q(internal_reference__icontains=query) |
                                          models.Q(name__icontains=query) |
                                          models.Q(description__icontains=query)
                                          )


class ImageFile(models.Model):

    name = models.CharField("Name", max_length=100)
    internal_reference = models.CharField("Internal Reference", max_length=100, editable=False)
    description = models.TextField("Description", blank=True, null=True)
    image = models.ImageField(upload_to="OCR_image/input/", verbose_name="Input Image")
    create_at = models.DateTimeField("Create at", auto_now_add=True)
    updated_at = models.DateTimeField("Update at", auto_now=True)

    def __str__(self):
        return "{0:03d} - {1}".format(self.id, self.image)

    def execute_and_save_ocr(self):
        import time
        start_time = time.time()

        img = Image.open(self.image)
        txt = pytesseract.image_to_string(img, lang='eng')
        execution_time = time.time() - start_time
        ocr_txt = OCRText(image = self, text = txt, lang = "EN", execution_time = execution_time)
        ocr_txt.save()

        print("The image {0} was opened.".format(self.image))
        print('OCR: \n{0}\n'.format(txt))
        print('Execution Time: {0}'.format(ocr_txt.execution_time))

        return ocr_txt

    """
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('course_details', args=[], kwargs={'slug': self.slug})
    """

    def save(self, *args, **kwargs):

        if not self.internal_reference:
            random_value = utils.random_value_generator(size=20)
            while ImageFile.objects.filter(internal_reference=random_value).exists():
                random_value = utils.random_value_generator(size=20)
            hash_value = hashlib.md5(bytes(str(self.id) + str(random_value), 'utf-8'))
            self.internal_reference = hash_value.hexdigest()
        super(ImageFile, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "ImageFile"
        verbose_name_plural = "ImageFiles"
        ordering = ['id']

    objects = ImageFileManager()


class OCRText(models.Model):
    text = models.TextField("OCR text", blank=True)
    lang = models.TextField("Language", default="EN")
    execution_time = models.IntegerField("Execution Time", editable=False, null=True);
    image = models.ForeignKey('ImageFile', on_delete=models.CASCADE)
    create_at = models.DateTimeField("Create at", auto_now_add=True)
    updated_at = models.DateTimeField("Update at", auto_now=True)

    def __str__(self):
        return "{0:03d} - {1}".format(self.id, self.image.internal_reference)

    class Meta:
        verbose_name = "OCRText"
        verbose_name_plural = "OCRTexts"
        ordering = ['id']

uploader/forms.py
from django import forms
from uploader.models import ImageFile


class ImageFileForm(forms.ModelForm):
    class Meta:
        model = ImageFile
        fields = ('image', )

core/views.py
from django.shortcuts import render

# Create your views here.

uploader/views.py
from django.shortcuts import render, redirect
from uploader.forms import ImageFileForm
from uploader.models import ImageFile


def home(request):
    data = dict()

    image_form = ImageFileForm(request.POST or None, request.FILES or None)
    if image_form.is_valid():
        image = image_form.save()
        image.execute_and_save_ocr()
        redirect('home')

    image_list = ImageFile.objects.all().order_by('-id')

    data['image_form'] = image_form
    data['image_list'] = image_list
    return render(request, "uploader/index.html", data)

templates/base.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} OCR web{% endblock %}</title>

    {% block extrahead %} {% endblock %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css"
          integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
          crossorigin="anonymous">
    {% block extrastyle %} {% endblock %}

</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">OCR web</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home'%}">Home</a>
            </li>
        </ul>
    </div>
</nav>


<div class="container content my-5">

    {% block content %} {% endblock %}
</div>




<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js"
        integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp"
        crossorigin="anonymous"></script>
{% block extrascript %} {% endblock %}
</body>
</html>

templates/error404.html
{% extends "base.html" %}

{% block title %} Home{% endblock %}

{% block content %}
<h1>ERROR 404!</h1>
<p ></p>
{% endblock %}

templates/error500.html
{% extends "base.html" %}

{% block title %} Home{% endblock %}

{% block content %}
<h1>ERROR 500!</h1>
<p ></p>
{% endblock %}

uploader/templates/uploader/index.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %} Home {% endblock %}

{% block extrahead %} {% endblock %}

{% block extrastyle %}
<style>

    .clickable_img:hover {
        cursor: pointer;
    }
</style>

{% endblock %}

{% block extrascript %}
<script>
$('.custom-file-input').on('change', function() {
   let fileName = $(this).val().split('\\').pop();
   $(this).next('.custom-file-label').addClass("selected").html(fileName);
});


function show_img_details(img_path){
    $('#img_detail').attr("src", img_path);
    $('#img_detail_modal').modal('toggle');
}


</script>

{% endblock %}


{% block content %}

<div class="mt-5 text-center">
    <h1>OCR web</h1>
</div>

<div class="offset-md-2 col-md-8 my-5" id="image_form">
    <form action="#image_form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <div class="custom-file my-2">
                {{image_form.image|add_class:"custom-file-input"}}
                <label class="custom-file-label">{{ image_form.image.label }}</label>
                {% for error in field.errors %}
                <span class="badge badge-danger">{{ error }}</span>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </fieldset>
    </form>
</div>

<div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col" class="text-center">#</th>
            <th scope="col" class="d-none d-sm-table-cell">Internal Reference</th>
            <th scope="col" class="d-none d-md-table-cell">OCR Text</th>
            <th scope="col" class="text-center">Image</th>
        </tr>
        </thead>
        <tbody>
        {% for image in image_list %}
        <tr>
            <th scope="row">{{image.id}}</th>
            <td class="d-none d-sm-table-cell">{{image.internal_reference}}</td>
            {% with image.ocrtext_set.last as ocrtext%}
            <td class="d-none d-md-table-cell">{{ ocrtext.text|truncatechars:350}}</td>
            {% endwith%}
            <td class="text-center">
                <div class="clickable_img"  onclick="show_img_details('/media/{{image.image}}')">
                    <img class="img-fluid img-thumbnail " src="/media/{{image.image}}" alt="{{image.image}}" width="100" />
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


<div id="img_detail_modal" class="modal mt-5" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="img_detail" class="img-fluid" src="" alt="" />
            </div>
        </div>
    </div>
</div>


{% endblock %}